CREATE DATABASE Gatoschema;
CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    Password NVARCHAR(255) NOT NULL
);

-- Table: Posts
CREATE TABLE Posts (
    Id INT PRIMARY KEY IDENTITY,
    UserId INT NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

-- Table: Comments
CREATE TABLE Comments (
    Id INT PRIMARY KEY IDENTITY,
    PostId INT NOT NULL,
    UserId INT NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (PostId) REFERENCES Posts(Id) ON DELETE NO ACTION,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE NO ACTION
);

-- Table: Likes
CREATE TABLE Likes (
    Id INT PRIMARY KEY IDENTITY,
    PostId INT NOT NULL,
    UserId INT NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (PostId) REFERENCES Posts(Id) ON DELETE NO ACTION,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE NO ACTION
);

-- Table: Notifications
CREATE TABLE Notifications (
    Id INT PRIMARY KEY IDENTITY,
    UserId INT NOT NULL,
    Message NVARCHAR(MAX) NOT NULL,
    IsRead BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE NO ACTION
);

-- Table: Messages
CREATE TABLE Messages (
    Id INT PRIMARY KEY IDENTITY,
    SenderId INT NOT NULL,
    ReceiverId INT NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    SentAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (SenderId) REFERENCES Users(Id) ON DELETE NO ACTION,
    FOREIGN KEY (ReceiverId) REFERENCES Users(Id) ON DELETE NO ACTION
);

-- Table: Settings
CREATE TABLE Settings (
    Id INT PRIMARY KEY IDENTITY,
    UserId INT NOT NULL,
    Preference NVARCHAR(100) NOT NULL,
    Value NVARCHAR(255) NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE NO ACTION
);